<a href="https://colab.research.google.com/github/sanaaria/Algorithms-of-data-science/blob/main/Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd

In [38]:

#load data
################################################################

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [39]:
file_path = '/content/drive/MyDrive/data.xlsx'
data = pd.read_excel(file_path, sheet_name='Data')

In [40]:
# نمایش اطلاعات اولیه
print(data.head())
print(data.info())

       ID  C1   C2   C3   C4   C5   C6   C7   C8   C9  ...  C23  C24  C25  \
0  100001   1  1.0  2.0  NaN  1.0  1.0  1.0  2.0  2.0  ...  2.0  2.0  5.0
1  100002   1  1.0  1.0  2.0  2.0  2.0  2.0  1.0  2.0  ...  2.0  1.0  4.0
2  100003   1  NaN  2.0  1.0  1.0  2.0  2.0  1.0  1.0  ...  3.0  3.0  4.0
3  100005   2  1.0  2.0  1.0  1.0  NaN  1.0  2.0  2.0  ...  2.0  2.0  4.0
4  100006   1  1.0  2.0  1.0  2.0  2.0  1.0  1.0  1.0  ...  1.0  1.0  5.0

   C26  C27  C28  C29  C30  C31  C32
0  2.0  3.0  1.0  1.0  1.0  1.0  1.0
1  3.0  3.0  1.0  2.0  1.0  1.0  3.0
2  3.0  3.0  2.0  2.0  2.0  3.0  4.0
3  NaN  1.0  1.0  1.0  2.0  1.0  1.0
4  1.0  4.0  1.0  1.0  1.0  3.0  3.0

[5 rows x 33 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1508 entries, 0 to 1507
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      1508 non-null   int64
 1   C1      1508 non-null   int64
 2   C2      1109 non-null   float64
 3   C3      1388 non-null   float64
 4   C4      1254 non-null   float64
 5   C5      1444 non-null   float64
 6   C6      1387 non-null   float64
 7   C7      1395 non-null   float64
 8   C8      1361 non-null   float64
 9   C9      1348 non-null   float64
 10  C10     1440 non-null   float64
 11  C11     1494 non-null   float64
 12  C12     1457 non-null   float64
 13  C13     1347 non-null   float64
 14  C14     1406 non-null   float64
 15  C15     1508 non-null   int64
 16  C16     1508 non-null   int64
 17  C17     1508 non-null   int64
 18  C18     1503 non-null   float64
 19  C19     1508 non-null   int64
 20  C20     1507 non-null   float64
 21  C21     1503 non-null   float64
 22  C22     1506 non-null   float64
 23  C23     1490 non-null   float64
 24  C24     1429 non-null   float64
 25  C25     1451 non-null   float64
 26  C26     1466 non-null   float64
 27  C27     1256 non-null   float64
 28  C28     1478 non-null   float64
 29  C29     1493 non-null   float64
 30  C30     1476 non-null   float64
 31  C31     1440 non-null   float64
 32  C32     1407 non-null   float64
dtypes: float64(27), int64(6)
memory usage: 388.9 KB
None

In [41]:
# نصب کتابخانه fancyimpute در Google Colab
!pip install fancyimpute
from fancyimpute import IterativeImputer

Requirement already satisfied: fancyimpute in /usr/local/lib/python3.10/dist-packages (0.7.0)
Requirement already satisfied: knnimpute>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (0.1.0)
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (1.5.2)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (1.5.3)
Requirement already satisfied: cvxopt in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (1.3.2)
Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (7.4.4)
Requirement already satisfied: nose in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (1.3.7)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.16.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.10/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (3.5.0)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (0.6.7.post0)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (2.0.14)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (0.9.0)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (3.2.7)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (2.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (24.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (1.2.2)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (2.0.2)
Requirement already satisfied: qdldl in /usr/local/lib/python3.10/dist-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (0.1.7.post4)

In [42]:
from sklearn.preprocessing import OrdinalEncoder

In [43]:
# مشخص کردن نوع داده‌ها
# فرض کنید که ستون‌های C1 تا C5 نامینال و ستون‌های C12 تا C32 اوردینال هستند
nominal_columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10',
                   'C11', 'C13', 'C14', 'C15', 'C32']
ordinal_columns = ['C12', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22',
                   'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29', 'C30',
                   'C31']

# تبدیل داده‌های نامینال به عددی با استفاده از Label Encoding
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for col in nominal_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col].astype(str))  # تبدیل به رشته برای جلوگیری از خطا
    label_encoders[col] = le  # ذخیره انکودرها برای استفاده‌های بعدی



ordinal_encoder = OrdinalEncoder()
data[ordinal_columns] = ordinal_encoder.fit_transform(data[ordinal_columns])

In [44]:
data

,ID,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C23,C24,C25,C26,C27,C28,C29,C30,C31,C32
0,100001,0,0,1,2,0,0,0,1,1,...,1.0,1.0,4.0,1.0,2.0,0.0,0.0,0.0,0.0,0
1,100002,0,0,0,1,1,1,1,0,1,...,1.0,0.0,3.0,2.0,2.0,0.0,1.0,0.0,0.0,2
2,100003,0,2,1,0,0,1,1,0,0,...,2.0,2.0,3.0,2.0,2.0,1.0,1.0,1.0,2.0,3
3,100005,1,0,1,0,0,2,0,1,1,...,1.0,1.0,3.0,NaN,0.0,0.0,0.0,1.0,0.0,0
4,100006,0,0,1,0,1,1,0,0,0,...,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503,101306,0,1,1,0,1,1,1,0,0,...,3.0,2.0,0.0,1.0,1.0,3.0,1.0,3.0,NaN,3
1504,101773,1,2,1,1,1,0,1,0,0,...,2.0,3.0,1.0,2.0,3.0,3.0,2.0,3.0,2.0,2
1505,100182,1,0,0,1,0,1,0,1,1,...,1.0,0.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,0
1506,100432,0,2,1,0,1,1,1,0,0,...,3.0,3.0,3.0,0.0,NaN,2.0,2.0,1.0,NaN,3
1507,100833,0,1,1,0,1,2,0,0,0,...,3.0,2.0,0.0,0.0,1.0,3.0,3.0,3.0,3.0,3

In [45]:
from sklearn.model_selection import train_test_split

# جداسازی داده‌ها به مجموعه آموزشی و تست
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [46]:
imputer = IterativeImputer(max_iter=10, random_state=0)
train_data_imputed = imputer.fit_transform(train_data)
test_data_imputed = imputer.transform(test_data)

In [47]:
train_data_imputed = pd.DataFrame(train_data_imputed, columns=train_data.columns)
test_data_imputed = pd.DataFrame(test_data_imputed, columns=test_data.columns)

In [48]:
train_data_imputed

,ID,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C23,C24,C25,C26,C27,C28,C29,C30,C31,C32
0,100820.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,1.0,2.0,...,3.0,1.000000,2.0,1.0,1.000000,3.0,3.0,0.0,0.0,1.0
1,101248.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,2.0,...,1.0,1.000000,4.0,0.0,2.035814,0.0,0.0,0.0,2.0,2.0
2,100824.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.031952,4.0,3.0,3.000000,0.0,0.0,0.0,0.0,1.0
3,101273.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.000000,3.0,3.0,1.000000,2.0,1.0,0.0,0.0,1.0
4,101542.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,...,3.0,3.000000,0.0,0.0,0.000000,1.0,2.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,101556.0,0.0,1.0,1.0,1.0,2.0,1.0,0.0,1.0,0.0,...,2.0,0.000000,1.0,1.0,3.000000,0.0,1.0,1.0,1.0,2.0
1202,101794.0,0.0,2.0,1.0,1.0,1.0,1.0,0.0,0.0,2.0,...,3.0,0.000000,4.0,2.0,2.460579,1.0,1.0,1.0,1.0,2.0
1203,101183.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,2.000000,4.0,3.0,3.000000,0.0,0.0,0.0,0.0,4.0
1204,101679.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,3.0,0.000000,3.0,3.0,3.000000,0.0,0.0,0.0,0.0,0.0
1205,101552.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.000000,3.0,3.0,3.000000,1.0,0.0,0.0,0.0,0.0

In [49]:
test_data_imputed

,ID,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C23,C24,C25,C26,C27,C28,C29,C30,C31,C32
0,100796.0,0.0,0.0,1.0,2.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1.0,3.0,1.0,0.000000,0.0,0.0,0.0,0.00000,0.0
1,101584.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,2.0,4.0,3.0,2.882622,0.0,0.0,0.0,0.00000,0.0
2,100523.0,0.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,2.0,2.0,3.0,2.0,2.000000,1.0,3.0,1.0,1.53539,4.0
3,100801.0,1.0,0.0,1.0,2.0,0.0,1.0,0.0,1.0,1.0,...,3.0,0.0,4.0,2.0,3.000000,0.0,0.0,0.0,0.00000,0.0
4,101330.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,3.0,3.0,1.0,2.000000,0.0,1.0,0.0,0.00000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,101282.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,...,1.0,0.0,3.0,3.0,1.000000,0.0,1.0,0.0,1.00000,2.0
298,101360.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,3.0,3.000000,0.0,0.0,0.0,0.00000,0.0
299,100521.0,0.0,2.0,1.0,0.0,1.0,2.0,1.0,0.0,0.0,...,3.0,1.0,1.0,0.0,2.000000,0.0,3.0,3.0,3.00000,3.0
300,101762.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,3.0,1.0,1.0,0.000000,1.0,2.0,3.0,3.00000,3.0
301,101745.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,4.0,3.0,3.000000,0.0,0.0,0.0,0.00000,0.0

In [50]:
# فرض کنید که داده‌های پر شده در train_data_imputed و test_data_imputed هستند
X_train = train_data_imputed.drop(columns=['C5'])  # ویژگی‌ها
y_train = train_data_imputed['C5']  # متغیر هدف

X_test = test_data_imputed.drop(columns=['C5'])  # ویژگی‌ها
y_test = test_data_imputed['C5']  # متغیر هدف

In [51]:
# import pandas as pd
# from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# # فرض می‌کنیم داده‌ها در DataFrame به نام data هستند

# # 1. تبدیل ستون‌های اسمی (Nominal) به One-Hot Encoding
# nominal_columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C13', 'C14', 'C15', 'C32']

# one_hot_encoder = OneHotEncoder(sparse_output=False, drop='first')  # drop='first' برای جلوگیری از دام همخطی

# # اعمال One-Hot Encoding به ستون‌های اسمی
# X_nominal_encoded = one_hot_encoder.fit_transform(data[nominal_columns])

# # دریافت نام ستون‌های جدید پس از One-Hot Encoding
# nominal_encoded_df = pd.DataFrame(X_nominal_encoded, index=data.index, columns=one_hot_encoder.get_feature_names_out(nominal_columns))

# # به‌جای حذف ستون‌های قدیمی، داده‌های جدید را جایگزین آن‌ها می‌کنیم
# data = data.drop(columns=nominal_columns)  # حذف ستون‌های قدیمی
# data = pd.concat([data, nominal_encoded_df], axis=1)  # ادغام ستون‌های جدید با داده‌های اصلی

# # 2. تبدیل ستون‌های ترتیبی (Ordinal) به Label Encoding
# # لیست تمام ستون‌های ترتیبی (ordinal)
# ordinal_columns = list(set(data.columns) - set(nominal_encoded_df.columns))  # مابقی ستون‌ها

# label_encoder = LabelEncoder()

# # تبدیل هر ستون ترتیبی به عددی با جایگزینی آن
# for col in ordinal_columns:
#     data[col] = label_encoder.fit_transform(data[col])

# # DataFrame نهایی که شامل ستون‌های تبدیل شده است
# print(data.head())  # نمایش داده‌های نهایی